import { TypeAnimationProps } from "react-type-animation/dist/cjs/components/TypeAnimation/index.types";

const splashes: (string | TypeAnimationProps["sequence"])[] = [
  "Time = Money. Time + Money = Internet Squares.",
  "A big wall. 4u.",
  "Sponsored by Cling.",
  "New updates daily.",
  "Greatest innovation on Fantom since HOLO!",
  "Growing as fast as Andre's eyebags!",
  "POOOMP",
  "You have now been blackmailed.",
  "As big as CrescoFin",
  "Not a copy.",
  "Not a scam.",
  "Not a rugpull.",
  "Not a honeypot.",
  "$3.48!",
  "$68,789.63!",
  "Second best, right next to Solana.",
  "Now with 50x leverage!",
  "Now with $35m from Alameda!",
  "TPS is a faulty metric!",
  "As explained by Head of US operations!",
  "Now without Andre!",
  "Now with Andre!",
  "Absolutely decentralized!",
  "fInally! fArt!",
  "As seen on some F1 car idk",
  "Is that his only picture?",
  "NFTs are the future! yeah!",
  "jane come to our team",
  "Buy ZOO!",
  "He booght?",
  "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
  "*schlop* *schlop* *schlop* *schlop* *schlop* *schlo",
  "Wen Artion",
  "Sponsored by AlexD Vlogs",
  ".c fusd 1d",
  ".c ice 5m",
  ".c tshare 1w",
  "trust me bro"
]

export default splashes;